---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qualys.qualys.io
  resources:
  - qualyscloudagents
  - qualyscontainersecurities
  - qualysplatformconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qualys.qualys.io
  resources:
  - qualyscloudagents/finalizers
  - qualyscontainersecurities/finalizers
  - qualysplatformconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - qualys.qualys.io
  resources:
  - qualyscloudagents/status
  - qualyscontainersecurities/status
  - qualysplatformconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - use
  - watch
