## Qualys Operator Sample Configurations ##
resources:
- qualys_operator_platformconfig.yaml
- qualys_operator_containersecurity_standard.yaml
- qualys_operator_containersecurity_recommended.yaml
- qualys_operator_containersecurity_privileged.yaml
- qualys_operator_containersecurity_unprivileged.yaml
- qualys_operator_containersecurity_minimal.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
