apiVersion: qualys.io/v1
kind: QualysContainerSecurity
metadata:
  labels:
    app.kubernetes.io/name: qualys-nanny
    app.kubernetes.io/managed-by: kustomize
  name: qualys-container-security-unprivileged
  namespace: qualys
spec:
  platformConfigRef:
    name: qualys-platform
  containerSensor:
    enabled: true
    image:
      repository: qualys/qcs-sensor
      tag: "latest"
      pullPolicy: IfNotPresent
    mode: general
    k8sMode: true
    privilegeMode: unprivileged
    security:
      runtimeSocketGroup: 0
    scanning:
      enableImageScan: true
      enableContainerScan: true
      enableScaScan: true
      scanThreadPoolSize: 2
    storage:
      usePersistentStorage: false
    logging:
      logLevel: 3
  clusterSensor:
    enabled: true
    image:
      repository: qualys/cluster-sensor
      tag: "1.4.0-0"
    replicas: 1
    cloudProvider: SELF_MANAGED_K8S
    clusterName: my-cluster
    k8sCompliance: true
  admissionController:
    enabled: false
  runtimeSensor:
    enabled: false
  scheduling:
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
    priorityClassName: system-node-critical
