apiVersion: qualys.qualys.io/v1alpha1
kind: QualysPlatformConfig
metadata:
  labels:
    app.kubernetes.io/name: qualys-nanny
    app.kubernetes.io/managed-by: kustomize
  name: qualys-platform
spec:
  platform:
    serverUri: "https://qagpublic.qg2.apps.qualys.com/CloudAgent/"
  credentials:
    sourceType: secret
    secretRef:
      name: qualys-credentials
      namespace: qualys
