apiVersion: qualys.io/v1
kind: QualysPlatformConfig
metadata:
  labels:
    app.kubernetes.io/name: qualys-nanny
    app.kubernetes.io/managed-by: kustomize
  name: qualys-platform
spec:
  platform:
    serverUri: "https://cmsqagpublic.qg1.apps.qualys.ca/ContainerSensor"
    gatewayUrl: "https://gateway.qg1.apps.qualys.ca"
  credentials:
    sourceType: secret
    secretRef:
      name: qualys-credentials
      namespace: qualys
